[package]
name = 'kubocchi/kubocchi-blog'
version = '0.1.1'
description = 'Description for package kubocchi-blog'

# See more keys and definitions at https://docs.wasmer.io/registry/manifest

[[module]]
name = 'kubocchi-blog'
source = 'kubocchi-blog.wasm'
abi = 'wasi'

[module.interfaces]
wasi = '0.1.0-unstable'

[[command]]
name = 'kubocchi-blog'
module = 'kubocchi-blog'
runner = 'wasi'
